version: '3.7'

services:

  frontend:
    container_name: frontend
    build: ./
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start